server:
  port: 80

spring:
  application:
    name: cloud-order-service

# eureka配置
eureka:
  client:
    register-with-eureka: false #注册服务
    fetch-registry: true #需检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka #注册到注册中心